import { EventEmitter } from 'events';

export enum SystemEvent {
  PLAN_CREATED = 'SD_EVENT_PLAN_CREATED',
  PLAN_FAILED = 'SD_EVENT_PLAN_FAILED',
  BUILD_READY = 'SD_EVENT_BUILD_READY',
  TEST_COMPLETED = 'SD_EVENT_TEST_COMPLETED',
  AGENT_INITIALIZED = 'SD_EVENT_AGENT_INITIALIZED',
  AGENT_ERROR = 'SD_EVENT_AGENT_ERROR',
  TASK_STARTED = 'SD_EVENT_TASK_STARTED',
  TASK_COMPLETED = 'SD_EVENT_TASK_COMPLETED',
  TASK_FAILED = 'SD_EVENT_TASK_FAILED',
  PROVIDER_REGISTERED = 'SD_EVENT_PROVIDER_REGISTERED',
  PROVIDER_UNREGISTERED = 'SD_EVENT_PROVIDER_UNREGISTERED',
  PROVIDER_EXECUTED = 'SD_EVENT_PROVIDER_EXECUTED',
  PROVIDER_ERROR = 'SD_EVENT_PROVIDER_ERROR',
  REGISTRY_CLEARED = 'SD_EVENT_REGISTRY_CLEARED',
}

export const systemEvents = new EventEmitter();

systemEvents.setMaxListeners(50);
